- name: Install nginx
  apt:
    name: nginx
    state: present
    update_cache: yes
  become: yes

- name: Deploy custom index page
  template:
    src: index.html.j2
    dest: /var/www/html/index.html
  become: yes

- name: Ensure nginx running
  service:
    name: nginx
    state: started
  become: yes
